# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20170921_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
